### ISSUE TITLE
您好，能否实现js 触发选择框 

### ISSUE THREAD

**Issue by wangdengbin** [lquan529/citySelect#1]
您好，感谢您分享代码。我现在遇到了一个问题，想请教下您  能否直接用js触发弹出city选择层 选择后我通过onCallerAfter 来处理选择结果 ？

**Comment by lquan529** [comment]
不好意思，show的接口我没有返回，所以现在这个是没有这个功能的，我要更新一下版本才可以

**Comment by lquan529** [comment]
你好，版本已经更新，增加了显示和隐藏的接口
showDrop()

**Comment by wangdengbin** [comment]
您好，我试了下 貌似还是有点问题 

执行到 citySelect-1.0.4.js 876行的时候 city选择层又被隐藏了 ，我在index.html 中随便添加了一个点击事件
添加了一个 a标签 <a href='javascript:;' id='aaaaaa'>测试</a>
$('#aaaaaa').on('click',function(){
	singleSelect1.showDrop();
});

**Comment by wangdengbin** [comment]
好像是 citySelect-1.0.4.js  1048行 点击以外的地方就隐藏 这边的逻辑导致了隐藏

**Comment by lquan529** [comment]
最好在你的点击事件加阻止事件冒泡
event.stopPropagation();

$('#a').on('click', function(event){
	event.stopPropagation();
	singleSelect1.showDrop();
});

**Comment by wangdengbin** [comment]
嗯， 试过了 感谢
