### ISSUE TITLE
简称获取城市之后默认值展示问题

### ISSUE THREAD

**Issue by james7whm** [lquan529/citySelect#2]
您好，正常情况下简称获取后入库，但默认值必须是全称才能展示，判断条件改为以下条件是否合适
`cityArray[i] === value.name || cityArray[i] === value.shortName`
![image](https://user-images.githubusercontent.com/35658738/89510596-5cb3a500-d803-11ea-8c70-57e52214a4d3.png)

**Comment by lquan529** [comment]
Duplicate of # 是这样
